services:
  soloist:
    image: ghcr.io/hypercookie/soloist_docker:latest
    restart: unless-stopped

    env_file:
      - .env
    network_mode: host
    command:
      - /usr/local/bin/soloist
      - --device-name
      - ${DEVICE_NAME}
      - --api-key
      - ${SOLOIST_API_KEY}
      - --ws
      - 127.0.0.1:0
    labels:
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: [ "CMD-SHELL", "soloist ctl status" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  watchtower:
    image: 'nickfedor/watchtower:latest'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=86400
